version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://<EC2-IP>:3001  # <-- Replace with your actual EC2 IP on deploy

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=bank

  mysql:
    image: mysql:5.7
    platform: linux/amd64  # Optional on AMD64, keep for compatibility
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
    ports:
      - "3307:3306"  # localhost:3307 connects to MySQL inside container
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
